# Generated by Django 2.2.7 on 2019-12-07 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tank_monitoring', '0002_auto_20191125_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='height',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='tank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='tank_monitoring.Tank'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='tank_monitoring.Farm'),
        ),
    ]
